export const LIBRARY_SEARCH_SHOW = 'LIBRARY_SEARCH_SHOW';
export const LIBRARY_SEARCH_HIDE = 'LIBRARY_SEARCH_HIDE';
export const LIBRARY_SEARCH_FETCH = 'LIBRARY_SEARCH_FETCH';
export const LIBRARY_SEARCH_RESULT_CLOSE = 'LIBRARY_SEARCH_RESULT_CLOSE';

export const LIBRARY_UPDATE_CONTEXT = "LIBRARY_UPDATE_CONTEXT";
export const LIBRARY_SET_TAG = "LIBRARY_SET_TAG";
export const LIBRARY_SET_GROUP = "LIBRARY_SET_GROUP";
export const LIBRARY_REFRESH = "LIBRARY_REFRESH";
export const GROUPS_REFRESH = "GROUPS_REFRESH";
export const LIBRARY_CLEAN = "LIBRARY_CLEAN";

export const MODALS_SET_EXPORT_LANGUAGE = "MODALS_SET_EXPORT_LANGUAGE";
export const MODALS_SET_RECOGNIZED_TEXT = "MODALS_SET_RECOGNIZED_TEXT";

export const ROTATE_TRANSFORM_START = "ROTATE_TRANSFORM_START";
export const ROTATE_TRANSFORM = "ROTATE_TRANSFORM";
export const ROTATE_TRANSFORM_COMPLETE = "ROTATE_TRANSFORM_COMPLETE";

export const COMBINE_NOTES_START = "COMBINE_NOTES_START";
export const COMBINE_NOTES_COMPLETE = "COMBINE_NOTES_COMPLETE";

export const EDIT_CREATE_NOTE = "EDIT_CREATE_NOTE";
export const EDIT_MODE_INIT = "EDIT_MODE_INIT";
export const EDIT_MODE_FINALIZE = "EDIT_MODE_FINALIZE";
export const EDIT_NOTE_UPDATED = "EDIT_NOTE_UPDATED";
export const EDIT_NOTE_SAVE_ENABLED = "EDIT_NOTE_SAVE_ENABLED";
export const EDIT_SELECT_LAYER = "EDIT_SELECT_LAYER";
export const EDIT_ADD_LAYER = "EDIT_ADD_LAYER";
export const EDIT_MERGE_PREVIOUS = "EDIT_MERGE_PREVIOUS";
export const EDIT_DELETE_LAYER = "EDIT_DELETE_LAYER";
export const EDIT_COPY_LAYER = "EDIT_COPY_LAYER";
export const EDIT_PASTE_LAYER = "EDIT_PASTE_LAYER";
export const EDIT_PASTING = "EDIT_PASTING";
export const EDIT_UPDATE_PREVIEWS = "EDIT_UPDATE_PREVIEWS";
export const EDIT_LAYERS_CHANGED = "EDIT_LAYERS_CHANGED";

export const EDIT_SHOW_LAYER_PANE = "EDIT_SHOW_LAYER_PANE";
export const EDIT_HIDE_LAYER_PANE = "EDIT_HIDE_LAYER_PANE";
export const EDIT_TOOL_PICK = "EDIT_TOOL_PICK";

export const EDIT_INIT_SPLIT   = "EDIT_INIT_SPLIT";
export const EDIT_CANCEL_SPLIT = "EDIT_CANCEL_SPLIT";
export const EDIT_SET_SPLIT_INDEX  = "EDIT_SET_SPLIT_INDEX";

export const EDIT_BEGIN_SPLIT_NOTE = "EDIT_BEGIN_SPLIT_NOTE";
export const EDIT_APPLY_SPLIT_LAYER  = "EDIT_APPLY_SPLIT_LAYER";
export const EDIT_APPLY_SPLIT_NOTE  = "EDIT_APPLY_SPLIT_NOTE";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const EDIT_START_SAVE = "EDIT_START_SAVE";
export const EDIT_END_SAVE = "EDIT_END_SAVE";

export const LIVE_MODE_INIT = "LIVE_MODE_INIT";
export const LIVE_MODE_NEW_NOTE = "LIVE_MODE_NEW_NOTE";
export const LIVE_MODE_ADD_LAYER = "LIVE_MODE_ADD_LAYER";
export const LIVE_MODE_ADD_STROKE = "LIVE_MODE_ADD_STROKE";
export const LIVE_MODE_FINALIZE = "LIVE_MODE_FINALIZE";
export const LIVE_MODE_SET_PEN_TYPE = "LIVE_MODE_SET_PEN_TYPE";

export const SET_DEVICE = "SET_DEVICE";
export const SET_DEVICE_STATUS = "SET_DEVICE_STATUS";
export const SET_BATTERY_CHARGE = "SET_BATTERY_CHARGE";
export const SET_LAST_SYNC  = "SET_LAST_SYNC";
export const SET_SETTINGS = "SET_SETTINGS";
export const SET_PROFILE = "SET_PROFILE";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_SETTINGS_TAB_INDEX = "SET_SETTINGS_TAB_INDEX";

export const UPDATE_DOWNLOAD_PROGRESS = "UPDATE_DOWNLOAD_PROGRESS";

export const MIGRATION_COMPLETED =  "MIGRATION_COMPLETED";
export const CLOUD_SYNCING  = "CLOUD_SYNCING";
export const CLOUD_DOWNLOADING  = "CLOUD_DOWNLOADING";
export const TAGS_UPDATE = "TAGS_UPDATE";

export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_HIDE = "MODAL_HIDE";
export const WIZARD_SHOW = "WIZARD_SHOW";
export const WIZARD_HIDE = "WIZARD_HIDE";
export const WIZARD_SET_STEP = "WIZARD_SET_STEP";

export const UPDATE_STATE_APP  = "UPDATE_STATE_APP";
export const UPDATE_STATE_LIBRARY  = "UPDATE_STATE_LIBRARY";
export const UPDATE_STATE_EDIT  = "UPDATE_STATE_EDIT";
export const UPDATE_STATE_LIVE  = "UPDATE_STATE_LIVE";
