export const NOT_PAIRED = "NOT_PAIRED";
export const DISCONNECTED = "DISCONNECTED";
export const CONNECTED_NOT_CHARGING = "CONNECTED_NOT_CHARGING";
export const CONNECTED_CHARGING = "CONNECTED_CHARGING";
export const SEARCHING_LOADING = "SEARCHING_LOADING";
