export const WELCOME = "Welcome";
export const SETUP_DEVICE = "SetupDevice";
export const SWITCH_ON = "SwitchOn";
export const DISCOVERY = "Discovery";
export const BT_CONNECTION_WAITING = "BTConnectionWaiting";
export const BT_CONNECTION_ACCEPTED = "BTConnectionAccepted"; /////////
export const TAP_TO_CONFIRM = "TapToConfirm";
export const SET_NAME = "SetName";
export const SELECT_ORIENTATION = "SelectOrientation";
export const LOGIN = "Login";
export const COMPLETE = "Complete";
